name: deploy-project
run-name: Deploy this project
on: [push]
jobs:
    semgrep:
        runs-on: ubuntu-latest
        container:
          image: returntocorp/semgrep
    
        if: (github.actor != 'dependabot[bot]')
        steps:
          - uses: actions/checkout@v3
          - run: semgrep ci
            env:
              SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: '16'
            -   run: npm install
            -   run: npm run test
    
    deploy:
        needs: [semgrep, test]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: '16'
            -   run: npm install
            -   run: npm run build
        
            -   uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./build